# -*- coding: utf-8 -*-
"""resume analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRpcSGJVRm9BfmF-8ru8QUW7Z00Qd9ys
"""

!pip install -q pypdf sentence-transformers faiss-cpu groq gradio

import gradio as gr
import numpy as np
import faiss

from pypdf import PdfReader
from sentence_transformers import SentenceTransformer
from groq import Groq
from google.colab import userdata

print("Libraries imported successfully!")

groq_api_key = userdata.get("GROQ_API_KEY")

client = Groq(api_key=groq_api_key)

print("Groq connected successfully!")

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded successfully!")

from google.colab import files

uploaded = files.upload()

pdf_file = list(uploaded.keys())[0]

print("Uploaded file:", pdf_file)

reader = PdfReader(pdf_file)

pages_text = []
full_text = ""

for page_number, page in enumerate(reader.pages, start=1):
    page_text = page.extract_text() or ""

    pages_text.append({
        "page": page_number,
        "text": page_text
    })

    full_text += page_text + "\n"

print("Total pages:", len(reader.pages))
print("Total characters:", len(full_text))

print("\n--- Resume Text Preview ---\n")
print(full_text[:3000])

chunks = []
chunk_pages = []

chunk_size = 1000
overlap = 200

for page_data in pages_text:
    page_number = page_data["page"]
    page_text = page_data["text"]

    if not page_text.strip():
        continue

    start = 0

    while start < len(page_text):
        end = start + chunk_size

        chunk = page_text[start:end].strip()

        if chunk:
            chunks.append(chunk)
            chunk_pages.append(page_number)

        start += chunk_size - overlap

print("Total chunks:", len(chunks))
print("Total page references:", len(chunk_pages))

print("\n--- First Chunk ---\n")
print(chunks[0])
print("\nPage:", chunk_pages[0])

for i in range(min(5, len(chunks))):
    print(f"\n--- Chunk {i+1} | Page {chunk_pages[i]} ---")
    print(chunks[i][:500])

embeddings = embedding_model.encode(
    chunks,
    show_progress_bar=True
)

print("Embeddings created successfully!")
print("Number of chunks:", len(embeddings))
print("Embedding size:", embeddings.shape[1])

print(embeddings[0])

print(embeddings[0])

embeddings = np.array(embeddings).astype("float32")

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("FAISS index created successfully!")
print("Total vectors stored:", index.ntotal)
print("Vector dimension:", dimension)

print("FAISS is ready!")
print("Vectors:", index.ntotal)

def retrieve_context(question, k=5):

    # Convert question into embedding
    question_embedding = embedding_model.encode([question])
    question_embedding = np.array(question_embedding).astype("float32")

    # Search FAISS
    distances, indices = index.search(question_embedding, k)

    retrieved_chunks = []
    retrieved_pages = []

    for i in indices[0]:

        if i == -1:
            continue

        retrieved_chunks.append(chunks[i])
        retrieved_pages.append(chunk_pages[i])

    # Combine retrieved chunks
    context = "\n\n".join(retrieved_chunks)

    # Remove duplicate page numbers
    unique_pages = sorted(set(retrieved_pages))

    return context, unique_pages

def ask_resume(question):

    # Retrieve relevant information
    context, pages = retrieve_context(question)

    # Create prompt for Groq
    prompt = f"""
You are an AI Resume Analyzer.

Answer the user's question using ONLY the resume information provided below.

Rules:
- Do not invent information.
- Give only information relevant to the question.
- Keep the answer concise and clear.
- If the information is not available, say:
  "I could not find this information in the resume."

RESUME CONTEXT:
{context}

USER QUESTION:
{question}

ANSWER:
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer, pages

question = "What is the experience of the candidate?"

answer, pages = ask_resume(question)

print("Answer:\n")
print(answer)

print("\nRelevant Pages:", pages)

resume_data = {
    "chunks": [],
    "pages": [],
    "index": None
}

print("Resume storage created!")

def process_resume(pdf_path):

    reader = PdfReader(pdf_path)

    new_chunks = []
    new_pages = []

    chunk_size = 1000
    overlap = 200

    # Extract and chunk the PDF
    for page_number, page in enumerate(reader.pages, start=1):

        page_text = page.extract_text() or ""

        if not page_text.strip():
            continue

        start = 0

        while start < len(page_text):

            end = start + chunk_size

            chunk = page_text[start:end].strip()

            if chunk:
                new_chunks.append(chunk)
                new_pages.append(page_number)

            start += chunk_size - overlap

    if not new_chunks:
        return "❌ Could not extract text from this PDF."

    # Create embeddings
    new_embeddings = embedding_model.encode(
        new_chunks,
        show_progress_bar=False
    )

    new_embeddings = np.array(new_embeddings).astype("float32")

    # Create new FAISS index
    dimension = new_embeddings.shape[1]

    new_index = faiss.IndexFlatL2(dimension)

    new_index.add(new_embeddings)

    # Replace old resume data
    resume_data["chunks"] = new_chunks
    resume_data["pages"] = new_pages
    resume_data["index"] = new_index

    return f"✅ Resume processed successfully!\n\nPages: {len(reader.pages)}\nChunks: {len(new_chunks)}"

def retrieve_new_resume(question, k=3):

    if resume_data["index"] is None:
        return "", []

    question_embedding = embedding_model.encode([question])

    question_embedding = np.array(question_embedding).astype("float32")

    distances, indices = resume_data["index"].search(
        question_embedding,
        k
    )

    retrieved_chunks = []
    retrieved_pages = []

    for i in indices[0]:

        if i == -1:
            continue

        retrieved_chunks.append(resume_data["chunks"][i])
        retrieved_pages.append(resume_data["pages"][i])

    context = "\n\n".join(retrieved_chunks)

    unique_pages = sorted(set(retrieved_pages))

    return context, unique_pages

def answer_resume_question(question):

    if resume_data["index"] is None:
        return "⚠️ Please upload and process a resume first."

    context, pages = retrieve_new_resume(question)

    prompt = f"""
You are an AI Resume Analyzer.

Answer the user's question using ONLY the information from the resume context.

Rules:
- Do not invent information.
- Answer only what is relevant to the question.
- Keep the answer clear and professional.
- If the information is not available, say:
"I could not find this information in the resume."

RESUME CONTEXT:
{context}

USER QUESTION:
{question}

ANSWER:
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    answer = response.choices[0].message.content

    return answer

import gradio as gr

def process_resume_ui(pdf_file):
    if pdf_file is None:
        return "⚠️ Please upload a resume PDF first."

    return process_resume(pdf_file)


def ask_question_ui(question):
    if not question.strip():
        return "⚠️ Please enter a question."

    return answer_resume_question(question)


with gr.Blocks(title="AI Resume Analyzer") as demo:

    gr.Markdown(
        """
        # 📄 AI Resume Analyzer
        ### Upload any resume PDF and ask questions about it
        """
    )

    with gr.Row():

        pdf_file = gr.File(
            label="Upload Resume PDF",
            file_types=[".pdf"],
            type="filepath"
        )

        process_button = gr.Button(
            "⚙️ Process Resume",
            variant="primary"
        )

    status = gr.Textbox(
        label="Resume Status",
        interactive=False
    )

    gr.Markdown("### 💬 Ask Questions About the Resume")

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What are the candidate's technical skills?",
        lines=2
    )

    ask_button = gr.Button(
        "🤖 Ask AI",
        variant="primary"
    )

    answer = gr.Textbox(
        label="AI Answer",
        lines=8,
        interactive=False
    )

    process_button.click(
        fn=process_resume_ui,
        inputs=pdf_file,
        outputs=status
    )

    ask_button.click(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )

    question.submit(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )


demo.launch(share=True)

import gradio as gr

def process_resume_ui(pdf_file):
    if pdf_file is None:
        return "⚠️ Please upload a resume PDF first."

    return process_resume(pdf_file)


def ask_question_ui(question):
    if not question.strip():
        return "⚠️ Please enter a question."

    return answer_resume_question(question)


with gr.Blocks(title="AI Resume Analyzer") as demo:

    gr.Markdown(
        """
        # 📄 AI Resume Analyzer
        ### Upload any resume PDF and ask questions about it
        """
    )

    with gr.Row():

        pdf_file = gr.File(
            label="Upload Resume PDF",
            file_types=[".pdf"],
            type="filepath"
        )

        process_button = gr.Button(
            "⚙️ Process Resume",
            variant="primary"
        )

    status = gr.Textbox(
        label="Resume Status",
        interactive=False
    )

    gr.Markdown("### 💬 Ask Questions About the Resume")

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What are the candidate's technical skills?",
        lines=2
    )

    ask_button = gr.Button(
        "🤖 Ask AI",
        variant="primary"
    )

    answer = gr.Textbox(
        label="AI Answer",
        lines=8,
        interactive=False
    )

    process_button.click(
        fn=process_resume_ui,
        inputs=pdf_file,
        outputs=status
    )

    ask_button.click(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )

    question.submit(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )


demo.launch(share=True)

summary = generate_resume_summary()

print(summary)

def generate_resume_summary():

    if resume_data["index"] is None:
        return "⚠️ Please upload and process a resume first."

    context, pages = retrieve_new_resume(
        "Give me the candidate's overall resume information including education, skills, experience, internships, projects, certifications and strengths.",
        k=5
    )

    prompt = f"""
You are a professional AI Resume Analyzer.

Analyze the resume information below and create a concise professional summary.

Include these sections:

1. Candidate Profile
2. Education
3. Technical Skills
4. Work Experience
5. Internships
6. Projects
7. Certifications
8. Strengths

Rules:
- Use ONLY information present in the resume.
- Do not invent information.
- If information is not available, write "Not mentioned".
- Keep the summary clear and professional.

RESUME CONTEXT:
{context}
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content

summary = generate_resume_summary()

print(summary)

print(resume_data["index"])

import gradio as gr


def process_resume_ui(pdf_file):

    if pdf_file is None:
        return "⚠️ Please upload a resume PDF first."

    return process_resume(pdf_file)


def ask_question_ui(question):

    if not question.strip():
        return "⚠️ Please enter a question."

    return answer_resume_question(question)


def summary_ui():

    return generate_resume_summary()


with gr.Blocks(title="AI Resume Analyzer") as demo:

    gr.Markdown(
        """
        # 📄 AI Resume Analyzer
        ### Upload any resume PDF and analyze it using AI
        """
    )

    # Upload section
    gr.Markdown("## 📤 Upload Resume")

    pdf_file = gr.File(
        label="Upload Resume PDF",
        file_types=[".pdf"],
        type="filepath"
    )

    process_button = gr.Button(
        "⚙️ Process Resume",
        variant="primary"
    )

    status = gr.Textbox(
        label="Resume Status",
        interactive=False
    )

    # Summary section
    gr.Markdown("## 📊 Resume Analysis")

    summary_button = gr.Button(
        "📊 Analyze Resume",
        variant="primary"
    )

    summary = gr.Textbox(
        label="Resume Summary",
        lines=15,
        interactive=False
    )

    # Question section
    gr.Markdown("## 💬 Ask Questions")

    question = gr.Textbox(
        label="Your Question",
        placeholder="Example: What are the candidate's technical skills?",
        lines=2
    )

    ask_button = gr.Button(
        "🤖 Ask AI",
        variant="primary"
    )

    answer = gr.Textbox(
        label="AI Answer",
        lines=8,
        interactive=False
    )

    # Button actions

    process_button.click(
        fn=process_resume_ui,
        inputs=pdf_file,
        outputs=status
    )

    summary_button.click(
        fn=summary_ui,
        inputs=None,
        outputs=summary
    )

    ask_button.click(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )

    question.submit(
        fn=ask_question_ui,
        inputs=question,
        outputs=answer
    )


demo.launch(share=True)

